version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  app:
    build: ./
    ports:
      - '8000:8000'
    volumes:
      - ./src/:/app/
    environment:
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      debug: '1'
    entrypoint: sh
    command: ['-c', 'sleep 5; python ./manage.py runserver 0:8000']
    depends_on:
      - db
    links:
      - db:db
